### ISSUE TITLE
Version name and Tag creation as part of the CI/CD pipline

### ISSUE THREAD

**Issue by arunvijayanpillai** [shortcut/appshowcase-android#41]
### Info:
It is cool to have the name be automated too as part of the CICD pipline.  It is an internal app so that is maybe not such a big deal.  But if you want control over the naming, the way I have done it myself (took the concept from Vipps) is by adding the ability to deploy with a release branch.  Merges to master can keep their automated name, but if you want a named version you can use the task 

```
    - uses: mad9000/actions-find-and-replace-string@2
      id: version_name
      with:
        source: ${{ github.ref_name }}
        find: 'release/'        
        replace: ''
```
for example.  This would run with these rules:
```
on:
  push:
    branches: [ "release/*" ]
```

And if you pushed a branch named `release/1.0.0 `it would make a release named 1.0.0.  Just an idea.

It could also be nice to make a release in github for automatic tagging as well.  Something like this

```
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_name.outputs.value }}
        release_name: Release ${{ steps.version_name.outputs.value }}
        draft: false
        prerelease: false
```

| Property Type | Property name | Property Definition | Data type | Sample Data |
| -------------- | --------------- | ------------------ | ---------- | ------------- |
| Event Property | Some property name | some definition of the property | Numerical | 60 |
